apiVersion: apps/v1
kind: Deployment
metadata:
  name: csgeo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csgeo
  template:
    metadata:
      labels: 
        app: csgeo
        #version: v1
    spec:
      containers:
      - name: csgeo
        image: localhost:5000/csgeo
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: csgeo
spec:
  #type: ClusterIP
  #type: LoadBalancer
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31080
    name: http
  selector:
    app: csgeo
    #version: v1
