apiVersion: apps/v1
kind: Deployment
metadata:
  name: csgeo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: csgeo
  template:
    metadata:
      labels: # labelに下記の値を設定
        app: csgeo
        #version: v1
    spec:
      containers:
      - name: csgeo
        image: csgeo
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: csgeo
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  selector:
    app: csgeo
    version: v1
