apiVersion: apps/v1
kind: Deployment
metadata:
  name: csgeo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csgeo
  template:
    metadata:
      labels: 
        app: csgeo
        #version: v1
    spec:
      containers:
      - name: csgeo
        image: localhost:5000/csgeo
        ports:
        - containerPort: 80
        env:
          - name: APIKEY
            valueFrom:
              secretKeyRef:
                name: google-apikey
                key: apikey
---
apiVersion: v1
kind: Service
metadata:
  name: csgeo
spec:
  #type: ClusterIP
  #type: LoadBalancer
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31080
    name: http
  - protocol: TCP
    port: 443
    targetPort: 443
    nodePort: 31443
    name: https
  selector:
    app: csgeo
    #version: v1
