step1:
	kubectl create -f resourcedefinition.yaml

step2:
	kubectl create -f my-crontab.yaml
	kubectl get ct -o yaml

delete:
	kubectl delete -f my-crontab.yaml
	kubectl delete -f resourcedefinition.yaml

